language: generic

sudo: required

dist: trusty

services: docker

matrix:
  include:
    - env: LAB="lab1"
    - env: LAB="lab2"

script:
  - cd ${TRAVIS_BUILD_DIR}/${LAB}
  - chmod +x build.sh
  - ./build.sh

before_deploy:
  - sudo mv ${TRAVIS_BUILD_DIR}/${LAB}/report/latex/${LAB}.pdf ${TRAVIS_BUILD_DIR}/${LAB}/report/latex/${LAB}_report.pdf
  - sudo chmod 777 ${TRAVIS_BUILD_DIR}/${LAB}/report/latex/${LAB}_report.pdf
  
deploy:
  provider: releases 
  api_key: "$GITHUB_DEPLOY_TOKEN" 
  file: 
    - ${TRAVIS_BUILD_DIR}/${LAB}/report/latex/${LAB}_report.pdf
  skip_cleanup: true 
  on: 
    tags: true
